[package]
name = "cssparser_fii"
version = "0.1.2"
edition = "2021"

[lib]
crate-type = ["staticlib", "lib"]

[features]
headers = ["safer-ffi/headers"]

[dependencies]
cssparser = "0.34.0"
paste = "1.0.15"
safer-ffi = "0.1.11"
