function(add_cssparser_as_dependency TARGET_NAME)
    message(NOTICE "Adding CSSParser as dependency for ${TARGET_NAME}. Make sure to add as a submodule for your project, then include the cmake file.")
    set(CSSPARSER_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/include CACHE INTERNAL "")
    if(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
        set(CSSPARSER_LIBRARIES ${CSSPARSER_LIBRARIES} CACHE INTERNAL "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/release/c_cssparser.lib")
        execute_process(COMMAND "run.bat")
    elseif(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
        execute_process(COMMAND "run.sh")
        set(CSSPARSER_LIBRARIES ${CSSPARSER_LIBRARIES} CACHE INTERNAL "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/release/c_cssparser.a")
    endif()
endfunction()